name: PHP Codeception Tests - v1.9

on:
  push:

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-v1.9.yml@main
    with:
      module-id: external_calendar
      install-composer: true
      additional-module-id: calendar
      additional-module-composer: true
